### PR TITLE
BSPD update

### PR DESCRIPTION
**Pull request by Guimi22**
Changes have been made with respect to the previous version:
-Q1 and Q2 connection now in parallel, so when implausability occurs, SC opens.
-Voltage divider that sets the trigger to open SC is now at 6 V, so C9 discharges in aproximately 14 seconds when implausability has happen.
-SC relay normally open so LV must be connected to close SC.

### CODE REVIEW

**Review by dweggg — COMMENTED** [review]
changing relay from NC to NO might alter the logic, check if the inputs IN3+ and IN3- of U3 must be flipped

**Comment by Guimi22** [comment]
> changing relay from NC to NO might alter the logic, check if the inputs IN3+ and IN3- of U3 must be flipped
Forgot to mention that inputs IN3+ and IN3- of U3 were flipped with respect to the previous version, in order to achieve NO SC relay logic

**Comment by dweggg** [comment]
> > Forgot to mention that inputs IN3+ and IN3- of U3 were flipped with respect to the previous version, in order to achieve NO SC relay logic

doesn't seem like so

image old
image new

**Comment by Guimi22** [comment]
Note of clarification:
After checking on the BSPD PCB used at FS 2022/23 competitions and the FS rules for 2024, I came to the following conclusion:
-Logic implemented on previous version was that the Shutdown Chain relay was normally closed which can be rules incompliance (see  EV6.1.7), so opposite logic has been chosen to implement on this updated version and the main purpose of the PCB has been maintained.

**Comment by eTechRacing** [comment]
Its ok for me.

**Review by eTechRacing — APPROVED** [review]
OK.

**Review by bernat17 — APPROVED** [review]
Ok

**Pull request merged**
